add_library(MRILibrary STATIC IMPORTED)
find_library(MRILIBRARY_LIBRARY_PATH /usr/local/lib/ HINTS "${CMAKE_CURRENT_LIST_DIR}/../../")
set_target_properties(MRILibrary PROPERTIES IMPORTED_LOCATION "${MRILIBRARY_LIBRARY_PATH}")
